version: '3'

services:
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api
    ports:
      - 8080:80
    logging:
      driver: "none"

  api:
    hostname: api
    build: .
    environment:
      - MONGODB_URL=mongodb://root:example@mongo:27017/?replicaSet=rs0
      - PYTHONUNBUFFERED=1
    volumes:
      - ./src:/app
    ports:
      - 8000:8000
    depends_on:
      - mongo

  futures-data:
    build: .
    environment:
      - MONGODB_URL=mongodb://root:example@mongo:27017/?replicaSet=rs0
      - PYTHONUNBUFFERED=1
#    entrypoint: ["sleep", "infinity"]
    command: ["la_proj.data.main", "-s", "^RUT", "^IXIC", "^DJI", "^GSPC"]
#              "--fake", "True",

    volumes:
      - ./src/la_proj:/app/la_proj
      - ./tests:/app/tests
    depends_on:
      - mongo

  mongo:
    hostname: mongo
    image: 'bitnami/mongodb:latest'
    environment:
      MONGODB_ROOT_PASSWORD: example
      MONGODB_REPLICA_SET_MODE: primary
      MONGODB_REPLICA_SET_NAME: rs0
      MONGODB_REPLICA_SET_KEY: replicaSetKey
    logging:
      driver: "none"

  mongo-express:
    image: mongo-express
    restart: always
    depends_on:
      - mongo
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_SERVER: mongo
    logging:
      driver: "none"
