version: '3'

services:
  frontend:
    image: alekseystryukov/la_pro_front:latest
    depends_on:
      - api
    ports:
      - 8080:80
    logging:
      driver: "none"

  api:
    hostname: api
    image: alekseystryukov/la_pro:latest
    environment:
      - MONGODB_URL=mongodb://root:example@mongo:27017/?replicaSet=rs0
      - PYTHONUNBUFFERED=1
    depends_on:
      - mongo

  futures-data:
    image: alekseystryukov/la_pro:latest
    environment:
      - MONGODB_URL=mongodb://root:example@mongo:27017/?replicaSet=rs0
    command: ["la_proj.data.main", "-s", "^RUT", "^IXIC", "^DJI", "^GSPC"]
#              "--fake", "True",

    depends_on:
      - mongo

  mongo:
    hostname: mongo
    image: 'bitnami/mongodb:latest'
    environment:
      MONGODB_ROOT_PASSWORD: example
      MONGODB_REPLICA_SET_MODE: primary
      MONGODB_REPLICA_SET_NAME: rs0
      MONGODB_REPLICA_SET_KEY: replicaSetKey
    logging:
      driver: "none"

  mongo-express:
    image: mongo-express
    restart: always
    depends_on:
      - mongo
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_SERVER: mongo
    logging:
      driver: "none"
